### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT/CIR-KIT.github.io#1]
@Ry0 
このレポジトリは、CIR-KIT.github.ioに内容をすべて移したため、3日後に削除します

**Comment by Ry0** [comment]
CIR-KIT.github.ioレポジトリは消して欲しくないな〜  
Gazeboのレポジトリかな

**Comment by RyodoTanaka** [comment]
ごめん間違えたorz
Gazeboレポジトリの方です。
もう一回向こうでissueします。
